### ISSUE TITLE
Module not showing in or at sidebar position

### ISSUE THREAD

**Issue by commandanti** [GavickPro/Music-Free-Responsive-Joomla-Template#102] opened 2013-02-18 19:12 UTC
Hi All,

I am trying to add a module to the sidebar of the GK-Music template but is not showing at all.
only some postition are available and I love this template, can someone help..?
Documentation is very poor and not really clear.

Thank you for your help alrady.

Cheers,
Easy

**Comment by bkrztuk** [comment] 2013-02-19 21:20
Hi,
Are you sure that module is published on sidebar position and assigned for some menu items ? Please enable showing module title it will be easier to check whether it is added and of course give us your site URL

**Comment by ExtKerwejugend** [comment] 2013-03-12 01:43
Hello!
I have the same problem. The sidebar modules only show up when the content in mainbody is a contact form. Otherwise there is nothing loading.
I hope you can help me?!

http://test.die-kerwe.de/Joomla/ver_3-0

Proxy auth:
tempuser
temppass

User login:
tempuser
temppass

Many thanks in advance and best regards,

Stefan

**Comment by bkrztuk** [comment] 2013-03-12 07:31
Are you sure that you set this modules for all menu items ?

**Comment by ExtKerwejugend** [comment] 2013-03-12 10:41
Yes, I think so?!

**Comment by bkrztuk** [comment] 2013-03-12 13:00
I want to check the admin settings but I can access here >> http://test.die-kerwe.de/Joomla/ver_3-0/administrator I'm always re-direct to start page.

**Comment by ExtKerwejugend** [comment] 2013-03-12 14:46
Sorry, I left a security plugin enabled. Now I turned it off.

**Comment by ExtKerwejugend** [comment] 2013-03-13 13:24
Does now anybody have an idea? :-(

**Comment by bkrztuk** [comment] 2013-03-13 20:30
The problem is caused by JS errors, please look http://d.pr/i/IOns

jQuery library is not loaded, I've checked default template and the library is there so probably one of your 3rd party extensions remove this library from site.

**Comment by ExtKerwejugend** [comment] 2013-03-14 09:01
Ok, thanks. But how can I fix this?! And which extension causes this trouble?

**Comment by ExtKerwejugend** [comment] 2013-03-14 10:34
Alright, I fixed it. GK Music Template didn't ship with jQuery. So I just installed the following plugin and everything is working fine now. Thanks for your help!

http://www.joomlabamboo.com/joomla-extensions/jb-library-plugin-a-free-joomla-jquery-plugin

**Comment by bkrztuk** [comment] 2013-03-14 11:00
Ok, I'll close this issue.

**Closed as completed by bkrztuk** 2013-03-14 11:00 UTC
