### ISSUE TITLE
Undefined variable: GK_TEMPLATE_MODULE_STYLES

### ISSUE THREAD

**Issue by felixkat** [GavickPro/Music-Free-Responsive-Joomla-Template#29] opened 2012-08-16 02:26 UTC
as a result of doing  &tmpl=component I receive the following error.

Notice: Undefined variable: GK_TEMPLATE_MODULE_STYLES in Z:\ .....\templates\gk_music_free\component.php on line 24

I fixed mine by adding

<pre>
require_once('lib/framework/gk.const.php');
</pre>

in component.php

**Comment by dziudek** [comment] 2012-08-16 20:34
You're right - I've commited this fix :)

@bkrztuk  - please check if the problem appears in our other templates - if yes, please include the fix for the next Gavern update.

**Comment by felixkat** [comment] 2012-08-16 20:39
Cool.  I didn't submit the change this time just in case there was a quicker way.  ;)

**Comment by Cyberek** [comment] 2013-12-14 10:57
It seems like the problem is back with News in J3.x.
Here is user's report:
https://www.gavick.com/forums/news-joomla30/undefined-variable-gk-template-module-styles-31504.html?p=154463#p154463

**Comment by Heart1010** [comment] 2014-07-15 22:20
Had the same problem with J!3 Storebox template (newest version) and found that issue here over google.... fixed by above mentioned require.

**Comment by bkrztuk** [comment] 2014-07-23 12:52
Fix added to upcoming templates update.

**Closed as completed by bkrztuk** 2014-07-23 12:52 UTC
